### ISSUE TITLE
Making the plugin i18n ready

### ISSUE THREAD

**Issue by Nikschavan** [brainstormforce/network-wide-custom-code#10]
We should -
- [ ] Provide a `.pot` file with all the strings in the plugin, 
- [ ] Load the plugin text domain
- [ ] Change the text-domain to `network-wide-custom-code` from [smile](https://github.com/brainstormforce/network-wide-custom-code/blob/master/multisite-script.php#L146)

**Comment by vrundakansara** [comment]
Fixed here - c1b6522
