### ISSUE TITLE
Notice: get_blog_list is deprecated since version 3.0.0

### ISSUE THREAD

**Issue by maheshwaghmare** [brainstormforce/network-wide-custom-code#5]
Getting error - Notice: `get_blog_list` is **deprecated**<br/>
<img src="http://screenshots.sharkz.in/mahesh/2016/07/chrome_2016-07-20_17-03-41.png" />
## After Debug

It's showing to use function [wp_get_sites](https://developer.wordpress.org/reference/functions/wp_get_sites/)

BUT, It'll be deprecated in `WordPress v.4.6`

Check [core ticket](https://core.trac.wordpress.org/ticket/36994) for reference.

**Comment by vrundakansara** [comment]
Fixed!  719e3c9
