### ISSUE TITLE
user `network_admin_url()` instead of statically calling the network URL

### ISSUE THREAD

**Issue by Nikschavan** [brainstormforce/network-wide-custom-code#9]
Instead of calling the network url [statically](https://github.com/brainstormforce/network-wide-custom-code/blob/master/multisite-script.php#L60), we should use WordPress mu function [`network_admin_url()` ](https://developer.wordpress.org/reference/functions/network_admin_url/)

**Comment by vrundakansara** [comment]
Fixed here - c1b6522
